# Timeout limit for this lambda program
TIMEOUT_LIMIT_SECONDS = 780  # 13 mins
BUCKET_NAME = "dlc-test-tickets"
MAX_SCHEDULING_RETRIES = 5

# SageMaker inference (hosting) instance limits
P3_8XLARGE_INFERENCE = 0
C4_4XLARGE_INFERENCE = 0
P2_8XLARGE_INFERENCE = 0
C4_8XLARGE_INFERENCE = 0
TOTAL_INSTANCE_INFERENCE = 2

# SageMaker training instance limits
P3_8XLARGE_TRAINING = 4
C4_4XLARGE_TRAINING = 4
P2_8XLARGE_TRAINING = 0
C4_8XLARGE_TRAINING = 4
TOTAL_INSTANCE_TRAINING = 50

TRAINING_LIMIT = {
    "ml.p2.8xlarge": P2_8XLARGE_TRAINING,
    "ml.c4.4xlarge": C4_4XLARGE_TRAINING,
    "ml.c4.8xlarge": C4_8XLARGE_TRAINING,
    "ml.p3.8xlarge": P3_8XLARGE_TRAINING,
}

INFERENCE_LIMIT = {
    "ml.p2.8xlarge": P2_8XLARGE_INFERENCE,
    "ml.c4.4xlarge": C4_4XLARGE_INFERENCE,
    "ml.c4.8xlarge": C4_8XLARGE_INFERENCE,
    "ml.p3.8xlarge": P3_8XLARGE_INFERENCE,
}
